[variables]
NIXPACKS_NODE_VERSION = "22.14.0"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]
cacheDirectories = ["node_modules"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm run server"

[deploy]
restartPolicy = "ON_FAILURE"
maxRetries = 3